import { readFileSync } from 'node:fs';
import { generateKeyPairSync,randomBytes } from 'node:crypto';
import { createWorker } from './src/index.js';
import assert from 'node:assert/strict';
const db={subs:new Map(),claimed:new Set(),prepare(sql){return {bind(...args){this.args=args;return this;},async first(){if(sql==='SELECT 1')return {1:1};return db.subs.has(this.args[0])?{payload:db.subs.get(this.args[0])}:null;},async all(){return {results:[...db.subs.values()].map(payload=>({payload}))};},async run(){let changes=1;const a=this.args;if(sql.startsWith('INSERT OR IGNORE')){changes=db.claimed.has(a[0])?0:1;db.claimed.add(a[0]);}else if(sql.startsWith('INSERT INTO subscriptions'))db.subs.set(a[0],a[1]);else if(sql.startsWith('DELETE'))db.subs.delete(a[0]);return {meta:{changes}};}};}};
const jwk=generateKeyPairSync('ec',{namedCurve:'prime256v1'}).publicKey.export({format:'jwk'});
const p256dh=Buffer.concat([Buffer.from([4]),Buffer.from(jwk.x,'base64url'),Buffer.from(jwk.y,'base64url')]).toString('base64url');
const sub={endpoint:'https://fcm.googleapis.com/fcm/send/test',keys:{auth:randomBytes(16).toString('base64url'),p256dh}};
const env={DB:db,PUBLISH_TOKEN:'test-token',VAPID_PUBLIC_KEY:'test',VAPID_PRIVATE_KEY:'test'};
let sends=0,mode='ok',published=true;
const worker=createWorker(async(s,p)=>{sends++;assert.ok(p.url);assert.ok(p.tag);if(mode==='gone')return false;if(mode==='error')throw Error('secret endpoint must not appear');return true;},async()=>Response.json({date:'2026-10-08',status:published?'published':'demo'}));
const call=(path,data,auth=true,origin='https://gabberthomson.github.io')=>worker.fetch(new Request('https://worker.test'+path,{method:'POST',headers:{origin,...auth?{authorization:'Bearer test-token'}:{}},body:JSON.stringify(data)}),env);
assert.equal((await call('/api/subscribe',sub)).status,200);
assert.equal((await call('/api/subscribe',{...sub,endpoint:'https://internal.local/x'})).status,400);
assert.equal((await call('/api/publish',{date:'2026-10-08'},false)).status,401);
assert.equal((await call('/api/subscribe',sub,true,'https://evil.test')).status,403);
published=false;assert.equal((await call('/api/publish',{date:'2026-10-08'})).status,409);published=true;
const pair=await Promise.all([call('/api/publish',{date:'2026-10-08'}),call('/api/publish',{date:'2026-10-08'})]);assert.deepEqual(pair.map(r=>r.status).sort(),[200,409]);assert.equal(sends,1);
mode='error';assert.equal((await (await call('/api/test',{subscription:sub})).json()).failed,1);assert.equal(db.subs.size,1);
mode='gone';assert.equal((await (await call('/api/test',{subscription:sub})).json()).gone,1);assert.equal(db.subs.size,0);
await call('/api/subscribe',sub);await call('/api/unsubscribe',sub);assert.equal(db.subs.size,0);
assert.equal((await call('/api/publish',{date:'2026-02-30'})).status,400);
console.log('PASS: subscription, CORS, auth, publication gate, concurrent deduplication, failure retention, gone cleanup, unsubscribe, calendar validation.');
